# Generated by Django 2.1.3 on 2018-11-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.CharField(blank=True, choices=[('SF', 'Science fiction'), ('FA', 'Fantasy'), ('DR', 'Drama'), ('CO', 'Comedy'), ('HI', 'Historical'), ('RO', 'Romance'), ('AC', 'Action'), ('TR', 'Travel'), ('MY', 'Mystery'), ('AD', 'Adventure'), ('TH', 'Thriller')], max_length=50, null=True),
        ),
    ]
