# Generated by Django 2.1.3 on 2018-11-24 22:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181124_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SF', 'Science fiction'), ('FA', 'Fantasy'), ('DR', 'Drama'), ('CO', 'Comedy'), ('HI', 'Historical'), ('RO', 'Romance'), ('AC', 'Action'), ('TR', 'Travel'), ('MY', 'Mystery'), ('AD', 'Adventure'), ('TH', 'Thriller')], max_length=50, null=True),
        ),
    ]
