# Generated by Django 2.1.3 on 2018-11-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
    ]
