# Generated by Django 2.1.3 on 2018-11-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181130_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile_2',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='default-user-image.png', upload_to='pic'),
        ),
        migrations.DeleteModel(
            name='UserProfile_2',
        ),
    ]
